# dnsmasq DHCP/PxE server for F2 support

version: '2'
services:
  dnsmasq-dhcp-pxe:
    container_name: ${CONTAINERNAME}
    hostname: ${CONTAINER_HOSTNAME}
    restart: unless-stopped
    image: ${NAMESPACE}/${IMAGENAME}
    cap_add:
      - NET_ADMIN
    # environment:
    volumes:
      - "pxelinux-cfg:/var/lib/tftpboot/pxelinux.cfg"
      - "dnsmasq-conf:/etc/dnsmasq.conf.d"
      - "${EXTRA_PATH}:/var/lib/tftpboot/${EXTRA_NAME}"
    networks:
      iso-br1:
        ipv4_address: ${HUB_IP}
    command: >
      --dhcp-authoritative
      --conf-dir=/etc/dnsmasq.conf.d,*.conf

  web-server:
    restart: unless-stopped
    image: httpd
    volumes:
      - "webroot:/usr/local/apache2/htdocs"
    networks:
      iso-br1:
        ipv4_address: ${WEBSERVER_IP}


networks:
  iso-br1:
    driver: macvlan
    driver_opts:
      parent: ${HOST_BRIDGE}
    ipam:
      config:
        - subnet: ${SUBNET}
          gateway: ${BRIDGE_IP}

volumes:
  pxelinux-cfg:
  dnsmasq-conf:
  webroot:
